name: Build and Release IPA

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build IPA
        run: |
          mkdir -p build
          xcodebuild -scheme "ClashDash" \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -sdk iphoneos \
            -allowProvisioningUpdates \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive
          mkdir -p Payload
          cp -r build/App.xcarchive/Products/Applications/*.app Payload/
          zip -r Clash_Dash_unsigned.ipa Payload

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Clash_Dash_unsigned.ipa
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}